name: actions-tf
on: [push]
jobs:
        test_job:
                runs-on: ubuntu-latest
                steps:
                        - run: echo $TEST
                          env: 
                                TEST: $("${{github.event.repository.name}} TEST" | tr '[A-Z]' '[a-z]')
                        - run: echo $TEST
