name: actions-tf
on: [push]

jobs:
        test_job:
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout
                          uses: actions/checkout@v2
                        - name: build
                          run: docker build -t image .
                        - name: run
                          run: docker run image python test.py
                        - name: repo name
                          run: |
                                  echo ${{ toJson(github) }}
