name: actions-tf
on: [push]

jobs:
        test_job:
                runs-on: ubuntu-latest
                steps:
                        - name: build
                          run: docker build -t image .
                        - name: run
                          run: docker run image
