name: actions-tf
on: [push]

jobs:
        test_job:
                runs-on: ubuntu-latest
                container: Dockerfile
                steps:
                        - name: run
                          run: echo 'stuff'
