name: actions-tf
on: [push]

jobs:
        test_job:
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout
                          uses: actions/checkout@v2
                        - name: build
                          run: |
                                  ls
                                  docker build -t image .
                        - name: run
                          run: docker run image sh test.sh
